openapi: "3.0.0"
info:
  version: 1.0.1
  title: Claims API

paths:
  /api/v0/bulk-submission:
    post:
      tags:
        - bulk-submission
      summary: Create a bulk of provider submissions
      operationId: createBulkSubmission
      requestBody:
        description: A JSON containing details about a bulk submission
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkSubmissionBody'
      responses:
        '201':
          description: 'Created'
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'

components:
  schemas:
    BulkSubmissionBody:
      required:
        - id
        - data
        - status
        - error_code
        - error_description
        - created_by_user_id
        - created_on
        - modified_by_user_id
        - modified_on
      properties:
        id:
          type: string
          format: uuid
        data:
          type: object
          description: the object containing the complete JSON bulk submission data
        status:
          type: string
          description: allows to track the status of the bulk submission for validation purposes
        error_code:
          type: string
        error_description:
          type: string
        created_by_user_id:
          type: string
        created_on:
          type: string
        modified_by_user_id:
          type: string
        modified_on:
          type: string