CREATE OR REPLACE VIEW vw_claim_export
 AS
SELECT s.id AS "Submission Id",
       s.submission_period AS "Submission Period",
       s.area_of_law AS "Submission Area of Law",
       s.status AS "Submission Status",
       s.office_account_number AS "Office Account Number",
       s.created_on AS "Submission Created On",
       s.updated_on AS "Submission Updated On",
       c.id AS "Claim Id",
       c.status AS "Claim Status",
       c.schedule_reference AS "Schedule Reference",
       c.line_number AS "Line Number",
       c.case_reference_number AS "Case Reference Number",
       c.unique_file_number AS "Unique File Number",
       c.case_start_date AS "Case Start Date",
       c.case_concluded_date AS "Case Concluded Date",
       c.matter_type_code AS "Matter Type Code",
       c.crime_matter_type_code AS "Crime Matter Type Code",
       c.fee_scheme_code AS "Fee Scheme Code",
       c.fee_code AS "Fee Code",
       c.procurement_area_code AS "Procurement Area Code",
       c.access_point_code AS "Access Point Code",
       c.delivery_location AS "Delivery Location",
       c.representation_order_date AS "Representation Order Date",
       c.suspects_defendants_count AS "Suspects Defendants Count",
       c.police_station_court_attendances_count AS "Police Station Court Attendances Count",
       c.police_station_court_prison_id AS "Police Station Court Prison Id",
       c.dscc_number AS "DSCC Number",
       c.maat_id AS "MAAT Id",
       c.prison_law_prior_approval_number AS "Prison Law Prior Approval Number",
       c.is_duty_solicitor AS "Is Duty Solicitor",
       c.is_youth_court AS "Is Youth Court",
       c.scheme_id AS "Scheme Id",
       c.mediation_sessions_count AS "Mediation Sessions Count",
       c.mediation_time_minutes AS "Mediation Time Minutes",
       c.outreach_location AS "Outreach Location",
       c.referral_source AS "Referral Source",
       c.matched_claim_id AS "Matched Claim Id",
       c.created_on AS "Claim Created On",
       c.updated_on AS "Claim Updated On",
       client.client_forename AS "Client Forename",
       client.client_surname AS "Client Surname",
       client.client_date_of_birth AS "Client Date of Birth",
       client.unique_client_number AS "Unique Client Number",
       client.client_postcode AS "Client Postcode",
       client.gender_code AS "Gender Code",
       client.ethnicity_code AS "Ethnicity Code",
       client.disability_code AS "Disability Code",
       client.is_legally_aided AS "Is Legally Aided",
       client.client_type_code AS "Client Type Code",
       client.home_office_client_number AS "Home Office Client Number",
       client.cla_reference_number AS "CLA Reference Number",
       client.cla_exemption_code AS "CLA Exemption Code",
       client.client_2_forename AS "Client 2 Forename",
       client.client_2_surname AS "Client 2 Surname",
       client.client_2_date_of_birth AS "Client 2 Date of Birth",
       client.client_2_ucn AS "Client 2 UCN",
       client.client_2_postcode AS "Client 2 Postcode",
       client.client_2_gender_code AS "Client 2 Gender Code",
       client.client_2_ethnicity_code AS "Client 2 Ethnicity Code",
       client.client_2_disability_code AS "Client 2 Disability Code",
       client.client_2_is_legally_aided AS "Client 2 Is Legally Aided",
       claim_case.case_id AS "Case Id",
       claim_case.unique_case_id AS "Unique Case Id",
       claim_case.case_stage_code AS "Case Stage Code",
       claim_case.stage_reached_code AS "Stage Reached Code",
       claim_case.standard_fee_category_code AS "Standard Fee Category Code",
       claim_case.outcome_code AS "Outcome Code",
       claim_case.designated_accredited_representative_code AS "Designated Accredited Representative Code",
       claim_case.is_postal_application_accepted AS "Is Postal Application Accepted",
       claim_case.is_client_2_postal_application_accepted AS "Is Client 2 Postal Application Accepted",
       claim_case.mental_health_tribunal_reference AS "Mental Health Tribunal Reference",
       claim_case.is_nrm_advice AS "Is NRM Advice",
       claim_case.follow_on_work AS "Follow On Work",
       claim_case.transfer_date AS "Transfer Date",
       claim_case.exemption_criteria_satisfied AS "Exemption Criteria Satisfied",
       claim_case.exceptional_case_funding_reference AS "Exceptional Case Funding Reference",
       claim_case.is_legacy_case AS "Is Legacy Case",
       csf.advice_time AS "Advice Time",
       csf.travel_time AS "Travel Time",
       csf.waiting_time AS "Waiting Time",
       csf.net_profit_costs_amount AS "Net Profit Costs Amount",
       csf.net_disbursement_amount AS "Net Disbursement Amount",
       csf.net_counsel_costs_amount AS "Net Counsel Costs Amount",
       csf.disbursements_vat_amount AS "Disbursements VAT Amount",
       csf.travel_waiting_costs_amount AS "Travel Waiting Costs Amount",
       csf.net_waiting_costs_amount AS "Net Waiting Costs Amount",
       csf.is_vat_applicable AS "Is VAT Applicable",
       csf.is_tolerance_applicable AS "Is Tolerance Applicable",
       csf.prior_authority_reference AS "Prior Authority Reference",
       csf.is_london_rate AS "Is London Rate",
       csf.adjourned_hearing_fee_amount AS "Adjourned Hearing Fee Amount",
       csf.is_additional_travel_payment AS "Is Additional Travel Payment",
       csf.costs_damages_recovered_amount AS "Costs Damages Recovered Amount",
       csf.meetings_attended_code AS "Meetings Attended Code",
       csf.detention_travel_waiting_costs_amount AS "Detention Travel Waiting Costs Amount",
       csf.jr_form_filling_amount AS "JR Form Filling Amount",
       csf.is_eligible_client AS "Is Eligible Client",
       csf.court_location_code AS "Court Location Code",
       csf.advice_type_code AS "Advice Type Code",
       csf.medical_reports_count AS "Medical Reports Count",
       csf.is_irc_surgery AS "Is IRC Surgery",
       csf.surgery_date AS "Surgery Date",
       csf.surgery_clients_count AS "Surgery Clients Count",
       csf.surgery_matters_count AS "Surgery Matters Count",
       csf.cmrh_oral_count AS "CMRH Oral Count",
       csf.cmrh_telephone_count AS "CMRH Telephone Count",
       csf.ait_hearing_centre_code AS "AIT Hearing Centre Code",
       csf.is_substantive_hearing AS "Is Substantive Hearing",
       csf.ho_interview AS "HO Interview",
       csf.local_authority_number AS "Local Authority Number",
       cfd.fee_code AS "Fee Detail Fee Code",
       cfd.fee_type AS "Fee Detail Fee Type",
       cfd.fee_code_description AS "Fee Detail Fee Code Description",
       cfd.category_of_law AS "Fee Detail Category of Law",
       cfd.total_amount AS "Fee Detail Total Amount",
       cfd.vat_indicator AS "Fee Detail VAT Indicator",
       cfd.vat_rate_applied AS "Fee Detail VAT Rate Applied",
       cfd.calculated_vat_amount AS "Fee Detail Calculated VAT Amount",
       cfd.disbursement_amount AS "Fee Detail Disbursement Amount",
       cfd.requested_net_disbursement_amount AS "Fee Detail Requested Net Disbursement Amount",
       cfd.disbursement_vat_amount AS "Fee Detail Disbursement VAT Amount",
       cfd.hourly_total_amount AS "Fee Detail Hourly Total Amount",
       cfd.fixed_fee_amount AS "Fee Detail Fixed Fee Amount",
       cfd.net_profit_costs_amount AS "Fee Detail Net Profit Costs Amount",
       cfd.requested_net_profit_costs_amount AS "Fee Detail Requested Net Profit Costs Amount",
       cfd.net_cost_of_counsel_amount AS "Fee Detail Net Cost of Counsel Amount",
       cfd.net_travel_costs_amount AS "Fee Detail Net Travel Costs Amount",
       cfd.net_waiting_costs_amount AS "Fee Detail Net Waiting Costs Amount",
       cfd.detention_travel_and_waiting_costs_amount AS "Fee Detail Detention Travel and Waiting Costs Amount",
       cfd.jr_form_filling_amount AS "Fee Detail JR Form Filling Amount",
       cfd.travel_and_waiting_costs_amount AS "Fee Detail Travel and Waiting Costs Amount",
       cfd.bolt_on_total_fee_amount AS "Fee Detail Bolt On Total Fee Amount",
       cfd.bolt_on_adjourned_hearing_count AS "Fee Detail Bolt On Adjourned Hearing Count",
       cfd.bolt_on_adjourned_hearing_fee AS "Fee Detail Bolt On Adjourned Hearing Fee",
       cfd.bolt_on_cmrh_telephone_count AS "Fee Detail Bolt On CMRH Telephone Count",
       cfd.bolt_on_cmrh_telephone_fee AS "Fee Detail Bolt On CMRH Telephone Fee",
       cfd.bolt_on_cmrh_oral_count AS "Fee Detail Bolt On CMRH Oral Count",
       cfd.bolt_on_cmrh_oral_fee AS "Fee Detail Bolt On CMRH Oral Fee",
       cfd.bolt_on_home_office_interview_count AS "Fee Detail Bolt On Home Office Interview Count",
       cfd.bolt_on_home_office_interview_fee AS "Fee Detail Bolt On Home Office Interview Fee",
       cfd.bolt_on_substantive_hearing_fee AS "Fee Detail Bolt On Substantive Hearing Fee",
       cfd.escape_case_flag AS "Fee Detail Escape Case Flag",
       cfd.scheme_id AS "Fee Detail Scheme Id"
FROM submission s
         JOIN claim c ON c.submission_id = s.id
         LEFT JOIN client client ON client.claim_id = c.id
         LEFT JOIN claim_case claim_case ON claim_case.claim_id = c.id
         LEFT JOIN claim_summary_fee csf ON csf.claim_id = c.id
         LEFT JOIN calculated_fee_detail cfd ON cfd.claim_id = c.id;
