ALTER TABLE bulk_submission DROP CONSTRAINT chk_bulk_submission_status;
ALTER TABLE bulk_submission
    ADD CONSTRAINT chk_bulk_submission_status CHECK (status IN ('READY_FOR_PARSING', 'PARSING_COMPLETED', 'PARSING_FAILED', 'VALIDATION_FAILED', 'REPLACED', 'UNAUTHORISED', 'VALIDATION_SUCCEEDED', 'READY_FOR_SUBMISSION', 'DISCARDED'));

ALTER TABLE submission DROP CONSTRAINT chk_submission_status;
ALTER TABLE submission
    ADD CONSTRAINT chk_submission_status CHECK (status IN ('CREATED', 'READY_FOR_VALIDATION', 'VALIDATION_IN_PROGRESS', 'VALIDATION_SUCCEEDED', 'VALIDATION_FAILED', 'REPLACED', 'READY_FOR_SUBMISSION', 'DISCARDED'));
