CREATE TABLE audit_revision (
  rev       SERIAL PRIMARY KEY,
  rev_ts    TIMESTAMPTZ,
  user_id   UUID
);

CREATE TABLE bulk_submission_aud (
    rev                 INTEGER,
    revtype             SMALLINT,
    id                  UUID,
    data                JSONB,
    status              TEXT,
    error_code          TEXT,
    error_description   TEXT,
    created_by_user_id  TEXT,
    created_on          TIMESTAMPTZ,
    updated_by_user_id  TEXT,
    updated_on          TIMESTAMPTZ,
    authorised_offices  TEXT,

    PRIMARY KEY (rev, id),
    FOREIGN KEY (rev) REFERENCES audit_revision (rev)
);

CREATE TABLE submission_aud (
    rev                                 INTEGER,
    revtype                             SMALLINT,
    id                                  UUID,
    bulk_submission_id                  UUID,
    office_account_number               TEXT,
    submission_period                   TEXT,
    area_of_law                         TEXT,
    status                              TEXT,
    crime_lower_schedule_number         TEXT,
    legal_help_submission_reference     TEXT,
    mediation_submission_reference      TEXT,
    previous_submission_id              UUID,
    is_nil_submission                   BOOLEAN,
    number_of_claims                    INTEGER,
    error_messages                      TEXT,
    created_by_user_id                  TEXT,
    created_on                          TIMESTAMPTZ,
    updated_by_user_id                  TEXT,
    updated_on                          TIMESTAMPTZ,
    provider_user_id                    TEXT,

    PRIMARY KEY (rev, id),
    FOREIGN KEY (rev) REFERENCES audit_revision (rev)
);

CREATE TABLE claim_aud (
    rev                                    INTEGER,
    revtype                                SMALLINT,
    id                                     UUID,
    submission_id                          UUID,
    status                                 TEXT,
    schedule_reference                     TEXT,
    line_number                            INTEGER,
    case_reference_number                  TEXT,
    unique_file_number                     TEXT,
    case_start_date                        DATE,
    case_concluded_date                    DATE,
    matter_type_code                       TEXT,
    crime_matter_type_code                 TEXT,
    fee_scheme_code                        TEXT,
    fee_code                               TEXT,
    procurement_area_code                  TEXT,
    access_point_code                      TEXT,
    delivery_location                      TEXT,
    representation_order_date              DATE,
    suspects_defendants_count              INTEGER,
    police_station_court_attendances_count INTEGER,
    police_station_court_prison_id         TEXT,
    dscc_number                            TEXT,
    maat_id                                TEXT,
    prison_law_prior_approval_number       TEXT,
    is_duty_solicitor                      BOOLEAN,
    is_youth_court                         BOOLEAN,
    scheme_id                              TEXT,
    mediation_sessions_count               INTEGER,
    mediation_time_minutes                 INTEGER,
    outreach_location                      TEXT,
    referral_source                        TEXT,
    matched_claim_id                       UUID,
    total_value                            NUMERIC,
    is_amended                             BOOLEAN DEFAULT FALSE,
    has_assessment                         BOOLEAN DEFAULT FALSE,
    version                                BIGINT DEFAULT 0,
    created_by_user_id                     TEXT,
    created_on                             TIMESTAMPTZ,
    updated_by_user_id                     TEXT,
    updated_on                             TIMESTAMPTZ,

    PRIMARY KEY (rev, id),
    FOREIGN KEY (rev) REFERENCES audit_revision (rev)
);

CREATE TABLE claim_case_aud (
    rev                                       INTEGER,
    revtype                                   SMALLINT,
    id                                        UUID,
    claim_id                                  UUID,
    case_id                                   TEXT,
    unique_case_id                            TEXT,
    case_stage_code                           TEXT,
    stage_reached_code                        TEXT,
    standard_fee_category_code                TEXT,
    outcome_code                              TEXT,
    designated_accredited_representative_code TEXT,
    is_postal_application_accepted            BOOLEAN,
    is_client_2_postal_application_accepted   BOOLEAN,
    mental_health_tribunal_reference          TEXT,
    is_nrm_advice                             BOOLEAN,
    follow_on_work                            TEXT,
    transfer_date                             DATE,
    exemption_criteria_satisfied              TEXT,
    exceptional_case_funding_reference        TEXT,
    is_legacy_case                            BOOLEAN,
    created_by_user_id                        TEXT,
    created_on                                TIMESTAMPTZ,
    updated_by_user_id                        TEXT,
    updated_on                                TIMESTAMPTZ,

    PRIMARY KEY (rev, id),
    FOREIGN KEY (rev) REFERENCES audit_revision (rev)
);

CREATE TABLE claim_summary_fee_aud (
    rev                                   INTEGER,
    revtype                               SMALLINT,
    id                                    UUID,
    claim_id                              UUID,
    advice_time                           INTEGER,
    travel_time                           INTEGER,
    waiting_time                          INTEGER,
    net_profit_costs_amount               NUMERIC,
    net_disbursement_amount               NUMERIC,
    net_counsel_costs_amount              NUMERIC,
    disbursements_vat_amount              NUMERIC,
    travel_waiting_costs_amount           NUMERIC,
    net_waiting_costs_amount              NUMERIC,
    is_vat_applicable                     BOOLEAN,
    is_tolerance_applicable               BOOLEAN,
    prior_authority_reference             TEXT,
    is_london_rate                        BOOLEAN,
    adjourned_hearing_fee_amount          INTEGER,
    is_additional_travel_payment          BOOLEAN,
    costs_damages_recovered_amount        NUMERIC,
    meetings_attended_code                TEXT,
    detention_travel_waiting_costs_amount NUMERIC,
    jr_form_filling_amount                NUMERIC,
    is_eligible_client                    BOOLEAN,
    court_location_code                   TEXT,
    advice_type_code                      TEXT,
    medical_reports_count                 INTEGER,
    is_irc_surgery                        BOOLEAN,
    surgery_date                          DATE,
    surgery_clients_count                 INTEGER,
    surgery_matters_count                 INTEGER,
    cmrh_oral_count                       INTEGER,
    cmrh_telephone_count                  INTEGER,
    ait_hearing_centre_code               TEXT,
    is_substantive_hearing                BOOLEAN,
    ho_interview                          INTEGER,
    local_authority_number                TEXT,
    created_by_user_id                    TEXT,
    created_on                            TIMESTAMPTZ,
    updated_by_user_id                    TEXT,
    updated_on                            TIMESTAMPTZ,

    PRIMARY KEY (rev, id),
    FOREIGN KEY (rev) REFERENCES audit_revision (rev)
);

CREATE TABLE client_aud (
    rev                         INTEGER,
    revtype                     SMALLINT,
    id                          UUID,
    claim_id                    UUID,
    client_forename             TEXT,
    client_surname              TEXT,
    client_date_of_birth        DATE,
    unique_client_number        TEXT,
    client_postcode             TEXT,
    gender_code                 TEXT,
    ethnicity_code              TEXT,
    disability_code             TEXT,
    is_legally_aided            BOOLEAN,
    client_type_code            TEXT,
    home_office_client_number   TEXT,
    cla_reference_number        TEXT,
    cla_exemption_code          TEXT,
    client_2_forename           TEXT,
    client_2_surname            TEXT,
    client_2_date_of_birth      DATE,
    client_2_ucn                TEXT,
    client_2_postcode           TEXT,
    client_2_gender_code        TEXT,
    client_2_ethnicity_code     TEXT,
    client_2_disability_code    TEXT,
    client_2_is_legally_aided   BOOLEAN,
    created_by_user_id          TEXT,
    created_on                  TIMESTAMPTZ,
    updated_by_user_id          TEXT,
    updated_on                  TIMESTAMPTZ,

    PRIMARY KEY (rev, id),
    FOREIGN KEY (rev) REFERENCES audit_revision (rev)
);

CREATE TABLE calculated_fee_detail_aud (
    rev                                         INTEGER,
    revtype                                     SMALLINT,
    id                                          UUID,
    claim_summary_fee_id                        UUID,
    claim_id                                    UUID,
    fee_code                                    TEXT,
    fee_type                                    TEXT,
    fee_code_description                        TEXT,
    category_of_law                             TEXT,
    total_amount                                NUMERIC,
    vat_indicator                               BOOLEAN,
    vat_rate_applied                            NUMERIC,
    calculated_vat_amount                       NUMERIC,
    disbursement_amount                         NUMERIC,
    requested_net_disbursement_amount           NUMERIC,
    disbursement_vat_amount                     NUMERIC,
    hourly_total_amount                         NUMERIC,
    fixed_fee_amount                            NUMERIC,
    net_profit_costs_amount                     NUMERIC,
    requested_net_profit_costs_amount           NUMERIC,
    net_cost_of_counsel_amount                  NUMERIC,
    net_travel_costs_amount                     NUMERIC,
    net_waiting_costs_amount                    NUMERIC,
    detention_travel_and_waiting_costs_amount   NUMERIC,
    jr_form_filling_amount                      NUMERIC,
    travel_and_waiting_costs_amount             NUMERIC,
    bolt_on_total_fee_amount                    NUMERIC,
    bolt_on_adjourned_hearing_count             INTEGER,
    bolt_on_adjourned_hearing_fee               NUMERIC,
    bolt_on_cmrh_telephone_count                INTEGER,
    bolt_on_cmrh_telephone_fee                  NUMERIC,
    bolt_on_cmrh_oral_count                     INTEGER,
    bolt_on_cmrh_oral_fee                       NUMERIC,
    bolt_on_home_office_interview_count         INTEGER,
    bolt_on_home_office_interview_fee           NUMERIC,
    bolt_on_substantive_hearing_fee             NUMERIC,
    escape_case_flag                            BOOLEAN,
    scheme_id                                   TEXT,
    created_by_user_id                          TEXT,
    created_on                                  TIMESTAMPTZ,
    updated_by_user_id                          TEXT,
    updated_on                                  TIMESTAMPTZ,

    PRIMARY KEY (rev, id),
    FOREIGN KEY (rev) REFERENCES audit_revision (rev)
);

CREATE TABLE matter_start_aud (
    rev                     INTEGER,
    revtype                 SMALLINT,
    id                      UUID,
    submission_id           UUID,
    schedule_reference      TEXT,
    category_code           TEXT,
    procurement_area_code   TEXT,
    access_point_code       TEXT,
    delivery_location       TEXT,
    number_of_matter_starts INTEGER,
    mediation_type          TEXT,
    created_by_user_id      TEXT,
    created_on              TIMESTAMPTZ,
    updated_by_user_id      TEXT,
    updated_on              TIMESTAMPTZ,

    PRIMARY KEY (rev, id),
    FOREIGN KEY (rev) REFERENCES audit_revision (rev)
);

CREATE TABLE validation_message_log_aud (
    rev                 INTEGER,
    revtype             SMALLINT,
    id                  UUID,
    submission_id       UUID,
    claim_id            UUID,
    type                TEXT,
    source              TEXT,
    display_message     TEXT,
    technical_message   TEXT,
    created_on          TIMESTAMPTZ,

    PRIMARY KEY (rev, id),
    FOREIGN KEY (rev) REFERENCES audit_revision (rev)
);


