CREATE TABLE claims (
    id                                       UUID PRIMARY KEY,
    submission_id                            UUID NOT NULL REFERENCES submissions(id),
    status                                   TEXT NOT NULL CHECK (status IN ('READY_TO_PROCESS', 'NOT_VALIDATED', 'INVALID', 'VALID')),
    schedule_reference                       TEXT NOT NULL,
    line_number                              INTEGER NOT NULL,
    case_reference_number                    TEXT NOT NULL,
    unique_file_number                       TEXT NOT NULL,
    case_start_date                          DATE NOT NULL,
    case_concluded_date                      DATE NOT NULL,
    matter_type_code                         TEXT NOT NULL,
    crime_matter_type_code                   TEXT,
    fee_scheme_code                          TEXT,
    fee_code                                 TEXT,
    procurement_area_code                    TEXT,
    access_point_code                        TEXT,
    delivery_location                        TEXT,
    representation_order_date                DATE,
    suspects_defendants_count                INTEGER,
    police_station_court_attendances_count   INTEGER,
    police_station_court_prison_id           TEXT,
    dscc_number                              TEXT,
    maat_id                                  TEXT,
    prison_law_prior_approval_number         TEXT,
    is_duty_solicitor                        BOOLEAN,
    is_youth_court                           BOOLEAN,
    scheme_id                                TEXT,
    mediation_sessions_count                 INTEGER,
    mediation_time_minutes                   INTEGER,
    outreach_location                        TEXT,
    referral_source                          TEXT,
    total_value                              NUMERIC,
    created_by_user_id                       UUID NOT NULL,
    created_on                               TIMESTAMPTZ NOT NULL,
    modified_by_user_id                      UUID,
    modified_on                              TIMESTAMPTZ
);
CREATE INDEX idx_claims_submission_id ON claims(submission_id);