CREATE TABLE claim_summary_fee (
   id                                       UUID NOT NULL,
   claim_id                                 UUID NOT NULL,
   advice_time                              INTEGER,
   travel_time                              INTEGER,
   waiting_time                             INTEGER,
   net_profit_costs_amount                  NUMERIC,
   net_disbursement_amount                  NUMERIC,
   net_counsel_costs_amount                 NUMERIC,
   disbursements_vat_amount                 NUMERIC,
   travel_waiting_costs_amount              NUMERIC,
   net_waiting_costs_amount                 NUMERIC,
   is_vat_applicable                        BOOLEAN,
   is_tolerance_applicable                  BOOLEAN,
   prior_authority_reference                TEXT,
   is_london_rate                           BOOLEAN,
   adjourned_hearing_fee_amount             NUMERIC,
   is_additional_travel_payment             BOOLEAN,
   costs_damages_recovered_amount           NUMERIC,
   meetings_attended_code                   TEXT,
   detention_travel_waiting_costs_amount    NUMERIC,
   jr_form_filling_amount                   NUMERIC,
   is_eligible_client                       BOOLEAN,
   court_location_code                      TEXT,
   advice_type_code                         TEXT,
   medical_reports_count                    INTEGER,
   is_irc_surgery                           BOOLEAN,
   surgery_date                             DATE,
   surgery_clients_count                    INTEGER,
   surgery_matters_count                    INTEGER,
   cmrh_oral_count                          INTEGER,
   cmrh_telephone_count                     INTEGER,
   ait_hearing_centre_code                  TEXT,
   is_substantive_hearing                   BOOLEAN,
   ho_interview                             TEXT,
   local_authority_number                   TEXT,
   created_by_user_id                       TEXT NOT NULL,
   created_on                               TIMESTAMPTZ NOT NULL,
   updated_by_user_id                       TEXT,
   updated_on                               TIMESTAMPTZ,

   CONSTRAINT pk_claim_summary_fee PRIMARY KEY (id),
   CONSTRAINT fk_claim_summary_fee_claim_id FOREIGN KEY (claim_id) REFERENCES claim(id)
);
CREATE INDEX ix_claim_summary_fee_claim_id ON claim_summary_fee(claim_id);