CREATE TABLE clients (
    id                          UUID PRIMARY KEY ,
    claim_id                    UUID NOT NULL REFERENCES claims(id),
    client_forename             TEXT,
    client_surname              TEXT,
    client_date_of_birth        DATE,
    unique_client_number        TEXT,
    client_postcode             TEXT,
    gender_code                 TEXT,
    ethnicity_code              TEXT,
    disability_code             TEXT,
    is_legally_aided            BOOLEAN,
    client_type_code            TEXT,
    home_office_client_number   TEXT,
    cla_reference_number        TEXT,
    cla_exemption_code          TEXT,
    client_2_forename           TEXT,
    client_2_surname            TEXT,
    client_2_date_of_birth      DATE,
    client_2_ucn                TEXT,
    client_2_postcode           TEXT,
    client_2_gender_code        TEXT,
    client_2_ethnicity_code     TEXT,
    client_2_disability_code    TEXT,
    client_2_is_legally_aided   BOOLEAN,
    created_by_user_id          TEXT NOT NULL,
    created_on                  TIMESTAMPTZ NOT NULL,
    modified_by_user_id         TEXT,
    modified_on                 TIMESTAMPTZ
);
CREATE INDEX idx_clients_claim_id ON clients(claim_id);
