# Default values for data-stewardship-payments.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: null
  tag: null

service_account:
  name: laa-data-claims-api-prod-service-account

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

