# Default values for data-stewardship-payments.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: null
  tag: null

service_account:
  name: laa-data-claims-api-staging-service-account

service:
  type: ClusterIP
  port: 8080

ingress:
  className: modsec-non-prod
  whitelist:
    enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "laa-data-claims-api-laa-data-claims-api-staging-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE"
      SecDefaultAction "phase:2,pass,log,tag:github_team=laa-data-stewardship-payments-team,tag:namespace=laa-data-claims-api-staging"
  hosts:
    - laa-data-claims-api-staging.cloud-platform.service.justice.gov.uk
  tls:
    - hosts:
      - domain: laa-data-claims-api-staging.cloud-platform.service.justice.gov.uk

resources:
  limits:
    cpu: 500m
    memory: 1G
  requests:
    cpu: 10m
    memory: 125Mi
