name: "Get merged release name"
description: 'Get the release name for the PR that has just been closed or merged into Main branch'

outputs:
  merged-branch-name:
    description: "Extracted merged branch name"
    value: ${{ steps.extract_branch.outputs.branch_name }}
  release-name-to-delete:
    description: "Extracted merged release name"
    value: ${{ steps.extract_release.outputs.release_name }}

runs:
  using: "composite"
  steps:

    - name: Get deleted/merged/closed branch name
      id: get_pr_branch
      shell: bash
      env:
        EVENT_NAME: "${{ github.event_name }}"
        EVENT_REF: "${{ github.event.ref }}"
        PR_HEAD_REF: "${{ github.event.pull_request.head.ref }}"
      run: |
        if [[ "${EVENT_NAME}" == "pull_request" ]]; then
          echo "BRANCH_NAME=${PR_HEAD_REF}" >> $GITHUB_OUTPUT
        elif [[ "${EVENT_NAME}" == "delete" ]]; then
          echo "BRANCH_NAME=${EVENT_REF}" >> $GITHUB_OUTPUT
        fi

    - name: Extract release name from branch name
      id: extract_release
      uses: ./.github/actions/extract_release_name_from_branch
      with:
        branch_name: ${{ steps.get_pr_branch.outputs.branch_name }}
