laa:
  springboot.starter.auth:
    authentication-header: "Authorization"
    authorized-clients: '[
        {
            "name": "test-runner",
            "roles": [
                "ALL"
            ],
            "token": "f67f968e-b479-4e61-b66e-f57984931e56"
        }
    ]'
    authorized-roles: '[
        {
            "name": "ALL",
            "URIs": [
                "/**"
            ]
        }
    ]'
    unprotected-uris: [ "/actuator/**", "/swagger-ui.html",
                        "/swagger-ui/**", "/v3/api-docs/**", "/favicon.ico", "/open-api-specification.yml"]

