name: "Get release name"
description: 'Get a release name'

inputs:
  pr-number:
    description: "Pull request number, if applicable"
    required: false

outputs:
  branch-name:
    description: "Extracted branch name"
    value: ${{ steps.et_release_and_branch.outputs.branch_name }}
  release-name:
    description: "Extracted release name"
    value: ${{ steps.et_release_and_branch.outputs.release_name }}

runs:
  using: "composite"
  steps:

    - name: Get release name and branch name
      id: get_release_and_branch
      shell: bash
      run: |
        if [ -n "${{ inputs.pr-number }}" ]; then
          echo "release-name=pr-${{ inputs.pr-number }}" >> $GITHUB_OUTPUT
          echo "branch-name=non-main" >> $GITHUB_OUTPUT
          echo "PR number provided: ${{ inputs.pr-number }}. Setting release-name to pr-${{ inputs.pr-number }} and branch-name to non-main."
        else
          echo "release-name=main" >> $GITHUB_OUTPUT
          echo "branch-name=main" >> $GITHUB_OUTPUT
          echo "No PR number provided. Setting release-name and branch-name to main."
        fi
