spring:
  jpa:
    open-in-view: false
  data:
    jpa:
      repositories:
        enabled: false
  flyway:
    enabled: false
  sql:
    init:
      mode: never

laa:
  springboot.starter.auth:
    authentication-header: "Authorization"
    authorized-clients: '[
        {
            "name": "test-runner",
            "roles": [
                "ALL"
            ],
            "token": "00000000-0000-0000-0000-000000000000"
        }
    ]'
    authorized-roles: '[
        {
            "name": "ALL",
            "URIs": [
                "/**"
            ]
        }
    ]'
    unprotected-uris: [ "/actuator/**", "/swagger-ui.html",
                        "/swagger-ui/**", "/v3/api-docs/**", "/favicon.ico", "/open-api-specification.yml"]

  dstew:
    payments:
      validator:
        provider-details-api:
          url: ${laa.provider-details-api.host}
          accessToken: ${PROVIDER_DETAILS_API_ACCESS_TOKEN}
          authHeader: "X-Authorization"
        fee-scheme-platform-api:
          host: ${FEE_SCHEME_PLATFORM_API_URL}
          url: ${laa.fee-scheme-platform-api.host}
          accessToken: ${FEE_SCHEME_PLATFORM_API_ACCESS_TOKEN}

        submission:
          minimum-period: ${SUBMISSION_VALIDATION_MINIMUM_PERIOD:APR-2025}