{{- if .Values.portForward.enabled }}
{{- if not (lookup "v1" "Service" .Release.Namespace "laa-data-claims-api-uat-postgresql") }}
apiVersion: v1
kind: Service
metadata:
  name: laa-data-claims-api-uat-postgresql
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "meta.helm.sh/release-name": "shared"
    "meta.helm.sh/release-namespace": {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    run: port-forward-pod
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
{{- end }}
{{- end }}
