{{- if .Values.portForward.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: laa-data-claims-api-uat-postgresql
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    run: port-forward-pod
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
{{- end }}