apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-claims-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-claims-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.management.port }}
      targetPort: {{ .Values.service.management.port }}
      protocol: TCP
      name: {{ .Chart.Name }}-management
  selector:
    {{- include "data-claims-api.selectorLabels" . | nindent 4 }}
