name: Build main

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build:
    if: ${{ github.event.pull_request.merged == true }}
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@90aa22bf1f55a39b4f10c4f7168356f0669eed77 # v1
    permissions:
      contents: write
      packages: write
    with:
      integration_test_task: 'integrationTest'
      create_tag: 'true'
      github_bot_username: 'laa-java-service-deployer'
      semgrep_check: 'false'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      github_app_id: ${{ vars.LAA_CCMS_CAAB_SERVICE_APP_ID }}
      github_app_private_key: ${{ secrets.LAA_CCMS_CAAB_SERVICE_KEY }}
      github_app_organisation: 'ministryofjustice'
