name: Deploy UAT preview

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

env:
  JAVA_VERSION: &JAVA_VERSION '25'
  JDK_DISTRIBUTION: &JDK_DISTRIBUTION 'corretto'

jobs:

  build-test:
    if: startsWith(github.head_ref || github.ref_name, 'openapi/') == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: *JAVA_VERSION
          distribution: *JDK_DISTRIBUTION

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@39e147cb9de83bb9910b8ef8bd7fff0ee20fcd6f # v6

      - name: Build and test
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test coverage verification
        run: ./gradlew jacocoTestCoverageVerification

      - name: Integration test
        run: ./gradlew integrationTest --tests '*IntegrationTest'

      - name: Publish api models package
        run: |
          version=$(git rev-parse --short HEAD)
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            version=${version}-SNAPSHOT
          fi
          ./gradlew :claims-data:api:publish -Pversion=$version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload service JAR artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: service-jar
          path: claims-data/service/build/libs/*.jar
          retention-days: 1

      - name: Upload checkstyle report for claims-data
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: checkstyle-report
          path: claims-data/service/build/reports/checkstyle
          retention-days: 14

      - name: Upload test report for claims-data
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: test-report
          path: claims-data/service/build/reports/tests
          retention-days: 14

      - name: Upload jacoco coverage report for claims-data
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: jacoco-coverage-report
          path: claims-data/service/build/reports/jacoco
          retention-days: 14

  sca-scan:
    needs:
      - build-test
    uses: ./.github/workflows/sca-analysis.yml
    permissions:
      contents: read
    with:
      java-version: *JAVA_VERSION
      distribution: *JDK_DISTRIBUTION
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}

  semgrep-scan:
    name: semgrep-security-scan
    needs: build-test
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run Semgrep scan
        run: semgrep scan --exclude-rule python.django.security.django-no-csrf-token.django-no-csrf-token --error --config auto

  vulnerability-scan-app:
    runs-on: ubuntu-latest
    needs:
      - build-test
    permissions:
      contents: read
      security-events: write
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SNYK_TEST_EXCLUDE: build,generated
      SNYK_TARGET_REFERENCE: main
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run Snyk to check app for vulnerabilities
        uses: snyk/actions/gradle@master # WARNING: Using mutable master branch - consider pinning to specific commit
        with:
          command: code test
          args: --severity-threshold=high

  vulnerability-scan-docker:
    runs-on: ubuntu-latest
    needs:
      - build-test
    permissions:
      contents: read
      security-events: write
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: *JAVA_VERSION
          distribution: *JDK_DISTRIBUTION

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@39e147cb9de83bb9910b8ef8bd7fff0ee20fcd6f # v6

      - name: Build app jar with gradle
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build local Docker image
        run: |
          docker build -t claims-data-scan .
          docker save claims-data-scan -o image.tar

      - name: Run Snyk to scan Docker image from tarball
        uses: snyk/actions/docker@master # WARNING: Using mutable master branch - consider pinning to specific commit
        with:
          image: image.tar
          args: --docker --severity-threshold=high --policy-path=.snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  ecr-publish-image:
    needs:
      - build-test
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/ecr-publish-image.yml@68d8f5aeccd47fa5baa1fe6c63269569b682e656 # v2
    permissions:
      contents: read
      id-token: write
      security-events: write
    with:
      jar_subproject: 'claims-data:service'
      image_version: ${{ github.sha }}
      java_version: '25'
      java_distribution: 'corretto'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      ecr_repository: ${{ vars.LAA_DATA_CLAIMS_API_ECR_REPOSITORY }}
      ecr_region: ${{ vars.LAA_DATA_CLAIMS_API_ECR_REGION }}
      ecr_role_to_assume: ${{ secrets.LAA_DATA_CLAIMS_API_ECR_ROLE_TO_ASSUME }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  pact-test:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/pact-and-publish.yml@dc4173bfc12f714d7e8cbdd9f524d00ef02e25c4 # v2
    needs:
      - ecr-publish-image
      - semgrep-scan
      - vulnerability-scan-app
      - vulnerability-scan-docker
      - sca-scan
    permissions:
      contents: write
      packages: write
      pull-requests: write
    with:
      pact_test_task: ":claims-data:service:pactTest"
      pacticipant_name: 'laa-data-claims-api'
      is_provider: true
      java_version: '25'
      java_distribution: 'corretto'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      pact_broker_url: ${{ secrets.PACT_BROKER_URL }}
      pact_broker_username: ${{ secrets.PACT_BROKER_USERNAME }}
      pact_broker_password: ${{ secrets.PACT_BROKER_PASSWORD }}

  deploy-uat-preview:
    runs-on: ubuntu-latest
    needs:
      - ecr-publish-image
      - pact-test
    environment: uat
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Extract release name
        id: extract_release_name_uat
        uses: ./.github/actions/get_release_name
        with:
          pr-number: ${{ github.event.pull_request.number }}

      - name: Can I deploy UAT?
        id: can_i_deploy_uat
        uses: ministryofjustice/laa-ccms-common-workflows/.github/actions/pact-can-i-deploy@dc4173bfc12f714d7e8cbdd9f524d00ef02e25c4 # v2
        with:
          pacticipant: 'laa-data-claims-api'
          environment: ${{ steps.extract_release_name_uat.outputs.release-name }}
          pact_broker_url: ${{ secrets.PACT_BROKER_URL }}
          pact_broker_username: ${{ secrets.PACT_BROKER_USERNAME }}
          pact_broker_password: ${{ secrets.PACT_BROKER_PASSWORD }}

      - name: Deploy UAT branch preview
        id: deploy_uat_branch
        uses: ./.github/actions/deploy_branch
        with:
          ecr-region: ${{ vars.LAA_DATA_CLAIMS_API_ECR_REGION }}
          ecr-role-to-assume: ${{ secrets.LAA_DATA_CLAIMS_API_ECR_ROLE_TO_ASSUME }}
          ecr-repository: ${{ vars.LAA_DATA_CLAIMS_API_ECR_REPOSITORY }}
          kube-cert: ${{ secrets.KUBE_CERT }}
          kube-token: ${{ secrets.KUBE_TOKEN }}
          kube-cluster: ${{ secrets.KUBE_CLUSTER }}
          kube-namespace: ${{ secrets.KUBE_NAMESPACE }}
          app-environment: uat
          pr-number: ${{ github.event.pull_request.number }}
          image-tag: ${{ needs.ecr-publish-image.outputs.published_image_version }}

      - name: Record UAT deployment to pact broker
        id: record_uat_deployment
        uses: ministryofjustice/laa-ccms-common-workflows/.github/actions/pact-record-deployment@dc4173bfc12f714d7e8cbdd9f524d00ef02e25c4 # v2
        with:
          pacticipant: 'laa-data-claims-api'
          environment: ${{ steps.extract_release_name_uat.outputs.release-name }}
          pact_broker_url: ${{ secrets.PACT_BROKER_URL }}
          pact_broker_username: ${{ secrets.PACT_BROKER_USERNAME }}
          pact_broker_password: ${{ secrets.PACT_BROKER_PASSWORD }}
