name: SCA - Software Composition Analysis

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
  workflow_dispatch:

permissions: {}

jobs:
  sca:
    name: Software Composition Analysis
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write
      security-events: write

    steps:
      - name: Run SCA
        uses: ministryofjustice/devsecops-actions/sca@f965eb1771ec66cfc41d7d57dc607fa6dfbc10ed # v1.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          renovate: "false"